# Generated by Django 5.1.2 on 2024-12-15 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mov_name', models.CharField(max_length=100)),
                ('mov_description', models.CharField(max_length=100)),
                ('mov_date', models.DateField(null=True)),
                ('mov_cost', models.IntegerField()),
                ('mov_type', models.CharField(max_length=50)),
                ('mov_image', models.CharField(max_length=200)),
                ('mov_video', models.CharField(max_length=200)),
                ('mov_duration', models.IntegerField()),
                ('mov_region', models.CharField(max_length=20)),
                ('mov_watcher', models.IntegerField(default=0)),
                ('mov_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('pass_word', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=10)),
                ('movie_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
            ],
        ),
        migrations.CreateModel(
            name='seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_name', models.CharField(max_length=10)),
                ('status', models.BooleanField()),
                ('room_foreign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.room')),
            ],
        ),
    ]
