# Generated by Django 5.1.2 on 2024-12-15 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_rename_movie_id_room_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.seat')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.users')),
            ],
        ),
    ]
