# Generated by Django 5.1.2 on 2024-12-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='date',
            field=models.DateField(default='2024-12-16', null=True),
        ),
    ]
